{{- if .Values.eventsourceServer.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfp-operator.fullname" . }}-run-completion-eventsource-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kfp-operator.eventsourceServer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kfp-operator.eventsourceServer.labels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.eventsourceServer.port }}
      protocol: TCP
      targetPort: grpc
{{- end -}}
