# Default values for kfp-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

containerRegistry: ""
nameOverride: ""
fullnameOverride: ""

controller:
  namespace: "kfp-operator-system"
  serviceAccount: "kfp-operator-controller-manager"

argo:
  serviceAccount: ""
  imagePullPolicy: Always
  kfpEndpoint: ""
  dataflowProject: ""
  pipelineStorage: ""
