apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-experiment-steps
spec:
  templates:
  - name: create
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '{{`{{workflow.parameters.kfp-endpoint}}`}}' --output json experiment create '{{`{{workflow.parameters.experiment-name}}`}}' | jq -r '."ID"'
      image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-argo-kfp-sdk:latest
      {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
      command:
      - ash
  - name: delete
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    script:
      source: |-
        set -e -o pipefail
        echo y | kfp-ext --endpoint '{{`{{workflow.parameters.kfp-endpoint}}`}}' --output json experiment delete '{{`{{workflow.parameters.experiment-id}}`}}'
      image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-argo-kfp-sdk:latest
      {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
      command:
      - ash
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-experiment
spec:
  arguments:
    parameters:
    - name: experiment-name
    - name: kfp-endpoint
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: '{{`{{steps.create.outputs.result}}`}}'
    steps:
    - - name: create
        templateRef:
          name: experiment-steps
          template: create
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-experiment
spec:
  arguments:
    parameters:
    - name: experiment-id
    - name: experiment-name
    - name: kfp-endpoint
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: '{{`{{steps.create.outputs.result}}`}}'
    steps:
    - - name: delete
        templateRef:
          name: experiment-steps
          template: delete
          clusterScope: true
    - - name: create
        continueOn:
          failed: true
        templateRef:
          name: experiment-steps
          template: create
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-experiment
spec:
  arguments:
    parameters:
    - name: experiment-id
    - name: kfp-endpoint
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: experiment-steps
          template: delete
          clusterScope: true
