apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pipeline-steps
spec:
  templates:
  - name: compile
    metadata: {}
    volumes:
    - name: shared
    container:
      name: pipeline
      image: "{{workflow.parameters.pipeline-image}}"
      imagePullPolicy: Never
      command:
      - python3
      args:
      - /shared/compile.py
      - --output_file
      - /tmp/pipeline.yaml
      - --pipeline_config
      - |
        {{workflow.parameters.compiler-config}}
      volumeMounts:
      - name: shared
        mountPath: /shared
    initContainers:
    - name: compile
      image: kfp-operator-argo-kfp-compiler:latest
      imagePullPolicy: Never
      mirrorVolumeMounts: true
      args:
      - /shared
    outputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
  - name: upload
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '{{workflow.parameters.kfp-endpoint}}' --output json pipeline upload --pipeline-name '{{workflow.parameters.pipeline-name}}' '/tmp/pipeline.yaml' | jq -r '."Pipeline Details"."Pipeline ID"'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
  - name: update
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '{{workflow.parameters.kfp-endpoint}}' --output json pipeline upload-version --pipeline-version '{{workflow.parameters.pipeline-version}}' --pipeline-id '{{inputs.parameters.pipeline-id}}' '/tmp/pipeline.yaml' | jq -r '."Version name"'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
      parameters:
      - name: pipeline-id
  - name: delete
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '{{workflow.parameters.kfp-endpoint}}' --output json pipeline delete '{{workflow.parameters.pipeline-id}}'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-pipeline
spec:
  arguments:
    parameters:
    - name: compiler-config
    - name: pipeline-image
    - name: pipeline-name
    - name: pipeline-version
    - name: kfp-endpoint
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: pipeline-id
        valueFrom:
          parameter: '{{steps.upload.outputs.result}}'
      - name: pipeline-version
        valueFrom:
          parameter: '{{steps.update.outputs.result}}'
    steps:
    - - name: compile
        templateRef:
          name: pipeline-steps
          template: compile
          clusterScope: true
    - - name: upload
        templateRef:
          name: pipeline-steps
          template: upload
          clusterScope: true
        arguments:
          artifacts:
          - from: '{{steps.compile.outputs.artifacts.pipeline}}'
            name: pipeline
    - - name: update
        templateRef:
          name: pipeline-steps
          template: update
          clusterScope: true
        continueOn:
          failed: true
        arguments:
          artifacts:
          - from: '{{steps.compile.outputs.artifacts.pipeline}}'
            name: pipeline
          parameters:
          - name: pipeline-id
            value: '{{steps.upload.outputs.result}}'
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-pipeline
spec:
  arguments:
    parameters:
    - name: compiler-config
    - name: pipeline-image
    - name: pipeline-id
    - name: pipeline-version
    - name: kfp-endpoint
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: pipeline-version
        valueFrom:
          parameter: '{{steps.update.outputs.result}}'
    steps:
    - - name: compile
        templateRef:
          name: pipeline-steps
          template: compile
          clusterScope: true
    - - name: update
        templateRef:
          name: pipeline-steps
          template: update
          clusterScope: true
        arguments:
          artifacts:
          - from: '{{steps.compile.outputs.artifacts.pipeline}}'
            name: pipeline
          parameters:
          - name: pipeline-id
            value: '{{workflow.parameters.pipeline-id}}'
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-pipeline
spec:
  arguments:
    parameters:
    - name: pipeline-id
    - name: kfp-endpoint
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: pipeline-steps
          template: delete
          clusterScope: true
